### PR TITLE
Option to use local font files instead of Google fonts, combined option for CDN use

### PR DESCRIPTION
**Pull request by dadosch**
This adds a new config option which allows the use of local font files instead of the fonts getting download through Google fonts, as there are privacy and maybe other negative implications with this.

The IBM Mono Plex font was fetched in main.css, while other have been fetched directly in the header partial, this has been moved.

### CODE REVIEW

**Comment by athul** [comment]
Woah @dadosch this is a massive PR. Thank you for creating this. I'll run the code and will get back to you 👍

**Comment by athul** [comment]
It seems like the fonts are not loaded while in Development. This was due to a relative paths in the `fonts.css`. Adding a `..` before the src url's tend to do the trick.
Kinda like this.
```diff
  src: local('IBM Plex Mono Medium Italic'), local('IBMPlexMono-MediumItalic'),
-       url('/fonts/ibm-plex-mono-v6-latin-500italic.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
-       url('/fonts/ibm-plex-mono-v6-latin-500italic.woff2') format('woff2'), /* Super Modern Browsers */
-       url('/fonts/ibm-plex-mono-v6-latin-500italic.woff') format('woff'), /* Modern Browsers */
-       url('/fonts/ibm-plex-mono-v6-latin-500italic.ttf') format('truetype'), /* Safari, Android, iOS */
-       url('/fonts/ibm-plex-mono-v6-latin-500italic.svg#IBMPlexMono') format('svg'); /* Legacy iOS */
}
src: local('IBM Plex Mono Medium Italic'), local('IBMPlexMono-MediumItalic'),
+       url('../fonts/ibm-plex-mono-v6-latin-500italic.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
+       url('../fonts/ibm-plex-mono-v6-latin-500italic.woff2') format('woff2'), /* Super Modern Browsers */
+       url('../fonts/ibm-plex-mono-v6-latin-500italic.woff') format('woff'), /* Modern Browsers */
+       url('../fonts/ibm-plex-mono-v6-latin-500italic.ttf') format('truetype'), /* Safari, Android, iOS */
+      url('../fonts/ibm-plex-mono-v6-latin-500italic.svg#IBMPlexMono') format('svg'); /* Legacy iOS */
}
```
Is it possible that you fix this?

**Comment by dadosch** [comment]
For me it worked fine when doing hugo serve, but it doesn't when hugo is serving in a subdirectory. Now it should work fine.

**Comment by athul** [comment]
> For me it worked fine when doing hugo serve, but it doesn't when hugo is serving in a subdirectory. Now it should work fine.

I'm curious, can you elaborate, just to understand.

The one I tested was on the site branch. I just pulled your changes and ran `hugo server -D`

**Comment by athul** [comment]
Also could you update the README too with the new config keys?

**Comment by dadosch** [comment]
> > For me it worked fine when doing hugo serve, but it doesn't when hugo is serving in a subdirectory. Now it should work fine.
> 
> I'm curious, can you elaborate, just to understand.
> 
> The one I tested was on the site branch. I just pulled your changes and ran `hugo server -D`

Ah, I didn't see the site branch, so what I used is the exampleSite folder from master branch (copied to a new directory, then moved the main theme in themes/archie).

The reason why it didn't work with the site branch at first, is that it's BaseUrl is `https://athul.github.io/archie/` (so in a subdirectory) while the exampleSite isn't in a subdirectory `/`  or `baseURL = "https://example.com"`

**Comment by athul** [comment]
Everything works fine ✨ . I've deployed it here https://archie-16.surge.sh

but here in the code can you update the main.css line 29 to `Fira Sans` and you're good to go 👍

**Review by athul — APPROVED** [review]
LGTM.


Thanks @dadosch

**Pull request merged**
