### PR TITLE
add / to make tag link work properly in terms.html

### PR DESCRIPTION
**Pull request by bumpsoo063**
It made a link to domaintags/tag-name/

### CODE REVIEW

**Comment by bumpsoo063** [comment]
probably it was a kind of missing something in toml or some where.. Somehow all of tags didnt link to proper pages( those linked domaintags/tag-name not domain/tags/tag-name)  at that moment I wrote. And with that / those linked to the pages properly So I though it would be correct to link. 
But Ive tested it a couple of times after your comment. It should't be a problem with the code.

**Comment by bumpsoo063** [comment]
well.. I forgot to remove histories before check the links. could you see this [site](https://bumpsoo063.life/tags/)? in my browser it links to domaintags/tag-name .
there is a tag which in Korean.

**Comment by bumpsoo063** [comment]
It was a problem in config.toml. I didn't add "/" at the end of baseURL.

**Comment by athul** [comment]
Glad you fixed it 🔥

**Pull request closed without merging**
