### PR TITLE
Add cache busting for CSS files via Hugo Pipes

### PR DESCRIPTION
**Pull request by arongergely**
I thought it's handy to have this. If the CSS changes on the prod. server, a user's browser will invalidate the cache and download the new style sheets.

The structure is impacted a bit, I moved the CSS files under  `/assets`. It's the default place for Hugo pipes

Note I did not touch the custom CSS files logic here:
https://github.com/athul/archie/blob/117808b653817e8ff7c7fc747361d2227de07a82/layouts/partials/header.html#L41-L46
It would break setups which already have custom CSS  configured. The custom CSS files would need to go under `/assets` 

However if you would like to have it I can add that.

ps: thanks for creating this neat Hugo theme!

### CODE REVIEW

**Comment by athul** [comment]
Hey @arongergely Thanks for the PR and sorry for the late reply. 

> It would break setups which already have custom CSS configured. The custom CSS files would need to go under /assets

I'm a tad concerned on this, maybe we could add that in the readme if anyone comes back to the repo if their site broke. If you're okay with that then everything is good to go, will merge after the update. 

> However if you would like to have it I can add that.

Also could you also elaborate on this, I'm a bit confused on this 😅

**Comment by arongergely** [comment]
Hi @athul, no problem. I see now that I was not clear about these points. Let me clarify:

1. AFAIK the changes in this PR would not break anything.
2. I spotted this 'custom CSS logic' in the header.html code but I left this part alone. 


The reason for **2.** is: Users who make use of the "custom CSS" feature probably put their extra CSS  files under the `/static` directory.  
If I was to add cache busting for these custom CSS, the files would be expected to live under the `/assets` directory.  Hence me saying this would break the site for such setups. The custom CSS would not be included unless the user would move it under `/assets` (and possibly editing the config.toml file to reflect this. )

Finally, 
>However if you would like to have it I can add that.

This remark was about whether I should touch this custom CSS logic anyway and add the cache busting.

If you think it's enough that we explain this change in the readme file, then I can do the changes for the custom css,
and write a few lines in the readme as well

hope it's clearer this time ;) 

what do to you think?

**Comment by athul** [comment]
Hey, thanks for the write-up 😄 
I don't think the new changes will affect current users unless they update the submodule often(which I don't think people usually do).

> If you think it's enough that we explain this change in the readme file, then I can do the changes for the custom css,
and write a few lines in the readme as well

This'll work(custom css changes and readme).

**Comment by arongergely** [comment]
@athul done ✔️

**Review by athul — APPROVED** [review]
Thank You. Everything looks :zap:

**Pull request merged**
