### PR TITLE
Add dark mode toggle

### PR DESCRIPTION
**Pull request by hsand**
Added a dark/light mode toggle. This can be configured with `mode="toggle"` in `config.toml`. The default is light, and changes are saved in localStorage for persistence.

### CODE REVIEW

**Comment by athul** [comment]
Hey, this PR looks 👌 . Could you also add the updates to the readme too?

**Comment by hsand** [comment]
Updated 😄

**Review by gautamkrishnar — APPROVED** [review]
LGTM 👍🏻  

Screenshot 2021-09-26 at 12 23 17 AM

Screenshot 2021-09-26 at 12 23 10 AM

**Comment by athul** [comment]
Cool then. 

Thanks @hsand 💖💖

**Pull request merged**
