### PR TITLE
Add custom CSS option - fixes issue #14

### PR DESCRIPTION
**Pull request by francisbarton**
Borrowed some code from https://github.com/gadenbuie/garrickadenbuie-com/blob/main/layouts/partials/head.html and blended it in. I hope the syntax is still valid and makes sense. I'm not sure if it ought to say `if isset .Site.Params "customCSS"` but I left it as `customcss` as you suggested.

### CODE REVIEW

**Review by athul — APPROVED** [review]
LGTM 👍 . Thanks for the PR @francisbarton 🎉  ✨

**Comment by VictorBersy** [comment]
Hey, thanks for the PR and the nice theme @athul!
I think it's supposed to be `href` instead of `ref`, no?

**Comment by athul** [comment]
🙈  Oops

**Comment by willwillis** [comment]
So what does the implementation look like? inside `hugo.toml` do I put the path to my custom css files like so?

```
[params]
	mode="toggle"
	customcss = ["custom.css"]
```

Then do I create that file under `./assets/css/custom.css`?

I've tried this as well as putting `custom.css` directly under `static` and hugo refuses to start the server.

I'm not sure if `$customstyle.Permalink` reference means I need to create the following in my config (which I tried and didn't work either).

```
[[params.customcss]]
Permalink = "custom.css"
```
Any help would be appreciated on how to implement custom CSS - the borrowed code in the top post is no longer available.

**Pull request merged**
